// Dependency-free admin behavior and data-safety checks. Run: node tests/test_admin.js
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const base = path.resolve(__dirname, '..');
const source = fs.readFileSync(base + '/app/assets/js/admin.js', 'utf8');
const html = fs.readFileSync(base + '/app/admin/index.html', 'utf8');
const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
const dom = Object.fromEntries(ids.map(id => [id, { id, hidden: false, disabled: false, innerHTML: '', textContent: '', value: id === 'period' ? '30' : '', listeners: {}, addEventListener(name, callback) { this.listeners[name] = callback; }, setAttribute(name, value) { this[name] = value; }, focus() { this.focused = true; }, select() { this.selected = true; } }]));
let responses = [{ status: 401, data: { error: 'Sign in' } }];
let requests = [];
let savedBlob;
let savedAnchor;
const fakeURL = class extends URL { static createObjectURL(blob) { savedBlob = blob; return 'blob:csv-test'; } static revokeObjectURL() {} };
const sandbox = {
  LIBRARY: {resources: [{id: 'test-resource', title: '<img src=x onerror=alert(1)>'}, {id: 'plain-resource', title: 'A human resource title'}]},
  document: { getElementById(id) { assert.ok(dom[id], id); return dom[id]; }, createElement() { savedAnchor = { click() { this.clicked = true; }, remove() { this.removed = true; } }; return savedAnchor; }, body: { appendChild() {} } },
  fetch(url, options) { requests.push({ url, options }); const response = responses.shift(); assert.ok(response, 'Unexpected API request'); return Promise.resolve({ ok: response.status < 400, status: response.status, json() { return Promise.resolve(response.data); } }); },
  Intl, Number, Object, Array, String, Promise, Date, Math, JSON, isNaN, encodeURIComponent, URL: fakeURL, Blob, setTimeout(callback) { callback(); }
};
const tick = () => new Promise(resolve => setImmediate(resolve));
const event = { id: 'a', type: 'share_complete', at: '2026-09-30T12:00:00Z', path: '/item.html', language: 'en', resource: 'test-resource', channel: 'copy_link', status: 'copied', country: 'US', referrer: 'https://example.com/path', shareId: ' =HYPERLINK("evil")', visitorId: 'v', sessionId: 's' };
const data = { summary: { visitors: 3, sessions: 4, pageViews: 6, shareIntents: 2, shareCompletions: 1, sharedVisits: 1, downloads: 1, transfers: 1 }, daily: [{date: '2026-09-29', visits: 4, shares: 1}, {date: '2026-09-30', visits: 2, shares: 1}], channels: [{name: 'copy_link', count: 1}], countries: [{name: 'US', count: 4}], languages: [{name: 'en', count: 4}], resources: [{name: 'test-resource', count: 1}, {name: 'plain-resource', count: 1}], events: [event, {...event, id: 'b', resource: 'plain-resource', type: 'download_complete', channel: 'download', status: 'browser_handoff', shareId: '', visitorId: '\t=CMD()', sessionId: '@HYPERLINK("evil")'}, {...event, id: 'c', resource: 'unlisted-resource', channel: 'native_share', status: 'handed_off', shareId: ''}], retentionDays: 90, analyzedEvents: 501, recentEventsTruncated: true, truncated: true };
(async () => {
  vm.runInNewContext(source, sandbox);
  await tick();
  assert.equal(dom['login-panel'].hidden, false);
  assert.equal(dom.dashboard.hidden, true);
  assert.equal(dom.message.hidden, true);
  assert.equal(requests[0].url, '/api/admin?days=30');
  dom['admin-password'].value = 'test-password';
  responses.push({status: 200, data: {ok: true}}, {status: 200, data});
  dom['login-form'].listeners.submit({ preventDefault() {} });
  await tick();
  assert.equal(dom.dashboard.hidden, false);
  assert.equal(dom['login-panel'].hidden, true);
  assert.equal(dom['admin-password'].value, '');
  assert.equal(requests[1].options.method, 'POST');
  assert.equal(requests[1].options.credentials, 'same-origin');
  assert.deepEqual(JSON.parse(requests[1].options.body), {action: 'login', password: 'test-password'});
  assert.equal(dom['report-warning'].hidden, false);
  assert.match(dom['event-note'].textContent, /newest 3 of 501/);
  assert.match(dom.metrics.innerHTML, /Confirmed share actions/);
  assert.match(dom.events.innerHTML, /&lt;img src=x onerror=alert\(1\)&gt;/);
  assert.doesNotMatch(dom.events.innerHTML, /<img src=x/);
  assert.match(dom.resources.innerHTML, /&lt;img src=x onerror=alert\(1\)&gt;/);
  assert.doesNotMatch(dom.resources.innerHTML, /<img src=x/);
  assert.match(dom.events.innerHTML, /A human resource title/);
  assert.match(dom.resources.innerHTML, /A human resource title/);
  assert.match(dom.events.innerHTML, /unlisted-resource/);
  assert.match(dom.resources.innerHTML, /· test-resource/);
  assert.match(dom['daily-chart'].innerHTML, /Sep 30/);
  assert.match(dom.channels.innerHTML, /Copied link/);
  assert.match(dom.events.innerHTML, /Browser download · unverified/);
  assert.match(dom.events.innerHTML, /Native share · unverified/);
  dom.export.listeners.click();
  assert.equal(savedAnchor.clicked, true);
  const csv = await savedBlob.text();
  assert.match(csv, /"' =HYPERLINK\(""evil""\)"/);
  assert.match(csv, /"'\t=CMD\(\)"/);
  assert.match(csv, /"'@HYPERLINK\(""evil""\)"/);
  assert.match(csv, /"test-resource"/);
  assert.doesNotMatch(csv, /A human resource title|<img src=x/);
  responses.push({status: 401, data: {error: 'Sign in'}});
  dom.refresh.listeners.click();
  await tick();
  assert.equal(dom.dashboard.hidden, true);
  assert.equal(dom.message.hidden, false);
  assert.match(dom.message.textContent, /session has ended/);
  assert.equal(dom.export.disabled, true);
  dom['admin-password'].value = 'wrong';
  responses.push({status: 401, data: {error: 'Invalid admin credentials.'}});
  dom['login-form'].listeners.submit({preventDefault() {}});
  await tick();
  assert.match(dom.message.textContent, /password was not accepted/);
  assert.equal(dom['admin-password'].focused, true);
  responses.push({status: 503, data: {error: 'Set EASYTRANSFER_ADMIN_PASSWORD.'}});
  dom['login-form'].listeners.submit({preventDefault() {}});
  await tick();
  assert.match(dom.message.textContent, /EASYTRANSFER_ADMIN_PASSWORD/);
  const empty = {...data, summary: Object.fromEntries(Object.keys(data.summary).map(key => [key, 0])), daily: [], channels: [], countries: [], languages: [], resources: [], events: [], analyzedEvents: 0, recentEventsTruncated: false, truncated: false};
  responses.push({status: 200, data: {ok: true}}, {status: 200, data: empty});
  dom['login-form'].listeners.submit({preventDefault() {}});
  await tick();
  assert.equal(dom.dashboard.hidden, false);
  assert.equal(dom['empty-overview'].hidden, false);
  assert.equal(dom['report-warning'].hidden, true);
  assert.equal(dom.export.disabled, true);
  assert.match(dom.events.innerHTML, /No events in this period/);
  responses.push({status: 200, data: {ok: true}});
  dom.logout.listeners.click();
  await tick();
  assert.deepEqual(JSON.parse(requests.at(-1).options.body), {action: 'logout'});
  assert.equal(dom.dashboard.hidden, true);
  assert.equal(dom['login-panel'].hidden, false);
  assert.equal(dom.logout.hidden, true);
  assert.equal(responses.length, 0);
  delete sandbox.LIBRARY;
  responses.push({status: 401, data: {error: 'Sign in'}});
  vm.runInNewContext(source, sandbox);
  await tick();
  dom['admin-password'].value = 'test-password';
  responses.push({status: 200, data: {ok: true}}, {status: 200, data});
  dom['login-form'].listeners.submit({preventDefault() {}});
  await tick();
  assert.equal(dom.dashboard.hidden, false);
  assert.match(dom.resources.innerHTML, />test-resource<\/span>/);
  assert.doesNotMatch(dom.resources.innerHTML, /A human resource title/);
  assert.equal(responses.length, 0);
  console.log('Admin checks passed: auth/login/logout, expiry/errors, catalogue titles and fallback, escaped rendering, UTC chart, partial/empty reports, unverified handoffs and CSV safety.');
})().catch(error => { console.error(error); process.exitCode = 1; });
